### PR TITLE
Use a newer version of nodejs as requested by the dev team

### PR DESCRIPTION
**Pull request by fahlmant**
Ticket 28747

### CODE REVIEW

**Comment by fahlmant** [comment]
@osuosl-cookbooks/chefs

**Comment by ramereth** [comment]
@fahlmant mind adding a serverspec test for verifying the version of nodejs installed?

**Comment by MorganEPatch** [comment]
Given the PM2 issues, it looks like the current plan is to avoid using newer ES6 features in our code and keep the servers at 0.12.7 for now, and look at upgrading in the longer term.

**Comment by ramereth** [comment]
@LyonesGamer so we can go ahead and close this?

**Comment by MorganEPatch** [comment]
@ramereth Yes.

**Pull request closed without merging**
